#!/usr/bin/env ruby
#
# This script cleans up `extracted` submission directories
# It should be safe to run at any time.
#

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

Course.all.each do |c|
  c.submissions.each do |s|
    if s.upload
      s.upload.cleanup_extracted!
    end
  end
end
