#!/usr/bin/env ruby
require 'beaneater'

bean = Beaneater.new("localhost:11300")
puts bean.stats.inspect

bean.tubes.each do |tube|
  puts "=== Tube: #{tube.name} ==="

  while tube.peek(:ready)
    job = tube.reserve
    puts "Clearing ready:"
    puts job.inspect
    puts job.delete
  end
  while tube.peek(:buried)
    job = tube.peek(:buried)
    puts "Clearing buried:"
    puts job.inspect
    puts job.delete
  end
end

