#!/usr/bin/env ruby
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

results = File.open(ARGV[0])

output = results.read

require 'tap_parser'
parser = TapParser.new(output)

puts parser.summary
